name: CD - Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]  # Only deploy after merge to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Package
        run: mvn clean package -DskipTests

      - name: Rename jar
        run: mv target/*.jar target/ridex-backend.jar

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: v-${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          s3_key: myapp-${{ github.run_number }}.jar
          file: target/ridex-backend.jar
